/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ultra/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные главной страницы
         * @description Данные для отображения главной страницы, включая промо-баннеры, инфо-блоки, популярные категории и отзывы
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            promo_banners?: {
                                id: number;
                                title: string;
                                image?: string;
                                alt_text?: string;
                                link?: string;
                                new_tab?: boolean;
                                bg_color?: string;
                                order?: number;
                            }[];
                            info_blocks?: {
                                id: number;
                                title: string;
                                description?: string;
                                image?: string;
                                image_alt?: string;
                                bg_color?: string;
                                link?: string;
                                order?: number;
                            }[];
                            new_products?: {
                                id: number;
                                name: string;
                                slug: string;
                                price: string;
                                regular_price?: string;
                                sale_price?: string;
                                on_sale?: boolean;
                                currency?: string;
                                image?: string;
                                link?: string;
                                rating?: number;
                                rating_count?: number;
                                in_stock?: boolean;
                            }[];
                            popular_categories?: {
                                id: number;
                                name: string;
                                slug: string;
                                description?: string;
                                count?: number;
                                image?: string;
                                link?: string;
                            }[];
                            sale_products?: {
                                id: number;
                                name: string;
                                slug: string;
                                price: string;
                                regular_price?: string;
                                sale_price?: string;
                                on_sale?: boolean;
                                currency?: string;
                                image?: string;
                                link?: string;
                                rating?: number;
                                rating_count?: number;
                                in_stock?: boolean;
                            }[];
                            reviews?: {
                                id: number;
                                title: string;
                                text?: string;
                                excerpt?: string;
                                author_name?: string;
                                rating?: number;
                                source?: string;
                                source_url?: string;
                                date?: string;
                                published_at?: string;
                                order?: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/layout/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные для отображения страницы
         * @description Данные для отображения страницы, включая меню, шапку и подвал, контакты и социальные сети
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug страницы */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            header: {
                                top_menu?: {
                                    id: number;
                                    title: string;
                                    url: string;
                                    target?: string;
                                    parent_id?: number;
                                    order?: number;
                                }[];
                                categories_menu?: {
                                    id: number;
                                    title: string;
                                    url: string;
                                    target?: string;
                                    parent_id?: number;
                                    order?: number;
                                }[];
                            };
                            contacts: {
                                address?: string;
                                phone_primary?: string;
                                phone_secondary?: string;
                                email?: string;
                                working_hours?: string;
                                map_iframe?: string;
                            };
                            social: {
                                id: string;
                                href: string;
                                alt: string;
                            }[];
                            page_metadata: {
                                title?: string;
                                description?: string;
                                image?: string;
                                url?: string;
                                date?: string;
                                author?: string;
                            };
                            footer: {
                                menu?: {
                                    id: number;
                                    title: string;
                                    url: string;
                                    target?: string;
                                    parent_id?: number;
                                    order?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные меню
         * @description Данные для отображения меню
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: {
                                id: number;
                                title: string;
                                url: string;
                                target?: string;
                                parent_id?: number;
                                order?: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/menus/{location}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные меню по местоположению
         * @description Данные для отображения меню по местоположению
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Расположение меню */
                    location: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            title: string;
                            url: string;
                            target?: string;
                            parent_id?: number;
                            order?: number;
                        }[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/catalog-menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ultra v1 catalog-menu */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/info-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Информационные блоки
         * @description Список инфо-блоков для главной страницы
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            info_blocks?: {
                                id: number;
                                title: string;
                                description?: string;
                                image?: string;
                                image_alt?: string;
                                bg_color?: string;
                                link?: string;
                                order?: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/promo-banners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Промо-баннеры
         * @description Список активных промо-баннеров для главной страницы
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            promo_banners?: {
                                id: number;
                                title: string;
                                image?: string;
                                alt_text?: string;
                                link?: string;
                                new_tab?: boolean;
                                bg_color?: string;
                                order?: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные отзывов
         * @description Данные для отображения отзывов клиентов
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reviews?: {
                                id: number;
                                title: string;
                                text?: string;
                                excerpt?: string;
                                author_name?: string;
                                rating?: number;
                                source?: string;
                                source_url?: string;
                                date?: string;
                                published_at?: string;
                                order?: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ultra/v1/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Данные глобальных настроек сайта
         * @description Данные для отображения глобальных настроек сайта, включая контакты, соцсети и популярные категории
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contacts?: {
                                address?: string;
                                phone_primary?: string;
                                phone_secondary?: string;
                                email?: string;
                                working_hours?: string;
                                map_iframe?: string;
                            };
                            social?: {
                                id: string;
                                href: string;
                                alt: string;
                            }[];
                            popular_categories?: {
                                id: number;
                                name: string;
                                slug: string;
                                description?: string;
                                count?: number;
                                image?: string;
                                link?: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
